BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Event" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"TournamentID"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("TournamentID") REFERENCES "Tournament"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Player" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "SetResult" (
	"ID"	TEXT NOT NULL UNIQUE,
	"EventID"	INTEGER NOT NULL,
	"winnerID"	INTEGER NOT NULL,
	"loserID"	INTEGER NOT NULL,
	"winnerScore"	INTEGER,
	"loserScore"	INTEGER,
	"duration"	BIGINT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EventID") REFERENCES "Event"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Standing" (
	"PlayerID"	INTEGER NOT NULL,
	"EventID"	INTEGER NOT NULL,
	"Standing"	INTEGER NOT NULL,
	PRIMARY KEY("PlayerID","EventID"),
	FOREIGN KEY("EventID") REFERENCES "Event"("ID") ON DELETE CASCADE,
	FOREIGN KEY("PlayerID") REFERENCES "Player"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Tournament" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"StartAt" BIGINT NOT NULL,
	PRIMARY KEY("ID")
);
COMMIT;
