BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Event" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"TournamentID"	INTEGER NOT NULL,
	PRIMARY KEY("ID"),
	FOREIGN KEY("TournamentID") REFERENCES "Tournament"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "EventRename" (
	"Name" TEXT NOT NULL,
	"Rename To" TEXT,
	"Delete" TEXT
);
CREATE TABLE IF NOT EXISTS "Player" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"DisplayName" TEXT,
	"ProfileUrl"	TEXT,
	"Main"	INTEGER,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "SetResult" (
	"ID"	TEXT NOT NULL UNIQUE,
	"EventID"	INTEGER NOT NULL,
	"winnerID"	INTEGER NOT NULL,
	"loserID"	INTEGER NOT NULL,
	"winnerScore"	INTEGER,
	"loserScore"	INTEGER,
	"duration"	BIGINT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EventID") REFERENCES "Event"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Standing" (
	"PlayerID"	INTEGER NOT NULL,
	"EventID"	INTEGER NOT NULL,
	"Standing"	INTEGER NOT NULL,
	PRIMARY KEY("PlayerID","EventID"),
	FOREIGN KEY("EventID") REFERENCES "Event"("ID") ON DELETE CASCADE,
	FOREIGN KEY("PlayerID") REFERENCES "Player"("ID") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "Tournament" (
	"ID"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"StartAt" BIGINT NOT NULL,
	PRIMARY KEY("ID")
);
CREATE TABLE IF NOT EXISTS "Stream" (
  Title TEXT,
  Game TEXT,
  player1 TEXT,
  player2 TEXT
);
CREATE TABLE IF NOT EXISTS "Controller" (
	"ID"	INTEGER,
	"Controller"	TEXT
);
CREATE TABLE IF NOT EXISTS "Character" (
	"ID"	INTEGER NOT NULL,
	"Game"	TEXT NOT NULL,
	"Character"	TEXT NOT NULL
);
COMMIT;
